#!/usr/bin/env python3
"""
localization.py - Dizionario traduzioni (i18n) e funzione tr() per MediaTidy.

Le chiavi generiche (stati, pulsanti comuni, dialoghi duplicati/cartella non vuota,
Opzioni, Crediti) sono condivise tra la scheda Film e la scheda Serie TV. Le chiavi
specifiche di una sola scheda sono prefissate "movie_" o "series_".
"""
from config import CONFIG, VERSION

STRINGS = {
    "it": {
        "app_title": f"MediaTidy v{VERSION} - Rinomina e Organizza Film e Serie TV",
        "tab_movies": "Film",
        "tab_series": "Serie TV",
        "options": "⚙ Opzioni",
        "format_btn": "Formato Nomi",
        "credits_btn": "Crediti & Privacy",
        "log_btn": "Log",
        "file_action": "Azione sui file:",
        "move": "Sposta (elimina originale)",
        "copy": "Copia (mantiene originale)",
        "action_move_short": "Sposta",
        "action_copy_short": "Copia",
        "exec_sel_suffix": "{n} sel.",
        "exec_all_suffix": "tutto ({n})",
        "drag_drop": "Trascina qui i file video o le cartelle",
        "add_files": "Aggiungi file…",
        "add_dir": "Aggiungi cartella…",
        "remove_sel": "Rimuovi selezionati",
        "clear_all": "Svuota",
        "test": "Test",
        "execute": "Esegui (Sposta/Copia)",
        "ready_status": "Pronto",
        "no_video_found": "Nessun nuovo file video trovato",

        "opts_title": "Opzioni e Configurazione",
        "tmdb_key": "Chiave API TMDB:",
        "tmdb_link_help": "Non hai una chiave? <a href='https://developer.themoviedb.org/docs/getting-started'>Ottienila qui (Guida TMDB)</a>",
        "dest_folder": "Destinazione:",
        "browse": "Sfoglia…",
        "tmdb_search_lang": "Lingua di ricerca TMDB:",
        "capitalization": "Capitalizzazione maiuscole:",
        "cap_1": "Prima lettera solo della prima parola",
        "cap_2": "Tutte le parole con la prima lettera maiuscola",
        "cap_3": "Tutte le parole escludendo articoli e congiunzioni",
        "unmount_chk": "Smonta il disco al termine (se montato dal programma)",
        "clean_dir_chk": "Rimuovi la cartella di origine se rimane vuota (solo in modalità Sposta)",
        "gui_lang_label": "Lingua Interfaccia (GUI Language):",
        "logs_dir_label": "Cartella log:",
        "ok": "Conferma",

        "format_title": "Formato Nomi",
        "format_tab_movies": "Film",
        "format_tab_series": "Serie TV",
        "dest_movies_label": "Destinazione Film:",
        "dest_series_label": "Destinazione Serie TV:",
        "title_mode_label": "Titolo:",
        "title_mode_original": "Solo titolo originale",
        "title_mode_localized": "Solo titolo localizzato",
        "title_mode_orig_loc": "Entrambi — Originale (Localizzato)",
        "title_mode_loc_orig": "Entrambi — Localizzato (Originale)",
        "movie_include_tmdb_id": "Includi l'ID TMDB nel nome della cartella",
        "movie_tmdb_id_note": "Se disattivato, titoli omonimi con lo stesso anno potrebbero finire nella stessa cartella.",
        "movie_include_country": "Includi il paese di produzione nel nome della cartella",
        "movie_include_director": "Includi il regista nel nome della cartella",
        "movie_download_poster": "Scarica il poster nella cartella di destinazione",
        "series_include_tmdb_id": "Includi l'ID TMDB nel nome della cartella della serie",
        "series_include_country": "Includi il paese di produzione (nel formato: Titolo (Paese, Anno))",
        "series_tmdb_id_note": "Se disattivato, serie omonime con lo stesso anno potrebbero finire nella stessa cartella.",
        "series_include_episode_title": "Includi il titolo dell'episodio nel nome del file",
        "series_download_show_poster": "Scarica il poster della serie",
        "series_download_season_poster": "Scarica il poster della stagione",

        "reset_auto_name": "Ripristina nome automatico",
        "series_ctx_edit_unified": "Modifica episodio e nome...",
        "series_edit_unified_title": "Modifica Episodio e Nome",
        "customize_name_chk": "Personalizza anche nome e cartella",

        "dup_title": "File/Cartella già Esistente",
        "dup_msg": "<b>Attenzione:</b> Il file o la cartella esiste già nella destinazione:<br><br><b>Cartella:</b> {folder}<br><b>File:</b> {file}<br><br>Come desideri procedere?",
        "dup_opt1": "1. Sovrascrivi il file esistente",
        "dup_opt2": "2. Rinomina in automatico (Aggiungi suffisso _1, _2...)",
        "dup_opt3": "3. Modifica personalizzata nome/cartella...",
        "dup_opt4": "4. Salta questo file",
        "dup_apply_all": "Applica la stessa scelta a tutti i duplicati rimanenti",

        "non_empty_dir_title": "Cartella di origine non vuota",
        "non_empty_dir_msg": "<b>Attenzione:</b> La cartella di origine contiene altri file residui:<br><br><b>Cartella:</b> {folder}<br><b>Dimensione totale residua:</b> {size}<br><br>Desideri eliminarla comunque?",
        "btn_yes": "Sì, elimina",
        "btn_yes_to_all": "Sì per tutte",
        "btn_no": "No, salta",
        "btn_open_folder": "Apri cartella",

        "search_btn": "Cerca",
        "skip_file": "Salta questo file",
        "ctx_custom": "Modifica personalizzata (Nome e Cartella)...",
        "ctx_tmdb": "Modifica Codice TMDB...",
        "ctx_lang": "Cerca in un'altra lingua per questo file...",
        "ctx_overwrite": "Forza Sovrascrittura",
        "ctx_suffix": "Aggiungi Suffisso _copia",
        "ctx_remove": "Rimuovi dalla lista",
        "custom_edit_title": "Modifica Personalizzata",
        "new_filename": "Nuovo Nome File:",
        "dest_subfolder": "Cartella Destinazione:",
        "edit_tmdb_title": "Modifica Codice TMDB",
        "tmdb_id_label": "ID Univoco TMDB:",
        "select_lang_title": "Seleziona Lingua Ricerca TMDB",
        "lang_label": "Lingua:",

        "missing_key_title": "Chiave Mancante",
        "missing_key_msg": "Inserisci la chiave API di TMDB nelle Opzioni.",
        "missing_dest_title": "Destinazione Mancante",
        "missing_dest_msg": "Indica la cartella di destinazione nelle Opzioni.",
        "done_test": "Test completato: {ready} file pronti",
        "done_action": "Operazione completata: {done} file elaborati",
        "notif_title": "MediaTidy - Operazione Completata",
        "notif_body": "Elaborazione di {done} file completata con successo sul target!",
        "unmounted_msg": " — disco smontato",
        "error_title": "Errore",
        "busy_title": "Operazione in corso",
        "busy_msg": "Attendi il completamento prima di chiudere.",

        "status_testing": "Test in corso…",
        "status_already_exists": "Esiste già",
        "status_ready": "Pronto",
        "status_ready_inplace": "Pronto (In-Place)",
        "status_skipped": "Saltato",
        "status_skipped_dup": "Saltato (Duplicato)",
        "status_moving": "Spostamento…",
        "status_copying": "Copia in corso…",
        "status_renaming": "Rinomina In-Place…",
        "status_done_moved": "Fatto (Spostato)",
        "status_done_copied": "Fatto (Copiato)",
        "status_done_inplace": "Fatto (Rinominato)",
        "status_ready_custom": "Pronto (Personalizzato)",
        "status_ready_overwrite": "Pronto (Sovrascrivi)",
        "status_ready_suffix": "Pronto (Suffisso)",
        "status_to_test": "Da testare",
        "status_error": "Errore",
        "status_tmdb_error": "Errore ID TMDB",
        "status_id_tmdb": "ID TMDB",
        "copy_suffix": "_copia",
        "invalid_custom_title": "Valori non validi",
        "invalid_custom_msg": "Il nome file è vuoto o contiene separatori di percorso, oppure la cartella è assoluta o contiene '..'.",

        # --- Film ---
        "movie_col_orig": "File originale",
        "movie_col_new": "Nuovo nome",
        "movie_col_dest": "Cartella di destinazione",
        "movie_col_tmdb": "Codice TMDB",
        "movie_col_status": "Stato",
        "movie_choice_title": "Conferma il film",
        "movie_no_res": "Nessun risultato trovato",
        "movie_uncertain": "Risultato incerto",
        "movie_choice_msg": " per «{guessed}».\nSeleziona il film corretto oppure cerca con un altro titolo.",

        # --- Serie TV ---
        "series_col_orig": "File / cartella di origine",
        "series_col_show": "Serie",
        "series_col_ep": "Stagione/Episodio",
        "series_col_new": "Nuovo nome",
        "series_col_dest": "Cartella di destinazione",
        "series_col_tmdb": "Codice TMDB (serie)",
        "series_col_status": "Stato",
        "series_choice_title": "Conferma la serie TV",
        "series_no_res": "Nessun risultato trovato",
        "series_uncertain": "Risultato incerto",
        "series_choice_msg": " per «{guessed}».\nSeleziona la serie corretta oppure cerca con un altro titolo.",
        "series_ctx_edit_ep": "Modifica Stagione/Episodio...",
        "series_edit_ep_title": "Modifica Stagione/Episodio",
        "series_season_label": "Stagione:",
        "series_episode_label": "Episodio (o primo di un range):",
        "series_episode_last_label": "Ultimo episodio (range, opzionale):",
        "series_status_unknown_ep": "Episodio non riconosciuto",
        "series_status_clip_skipped": "Ignorato (sample/trailer)",
        "series_add_release": "Aggiungi release…",
        "series_apply_release_chk": "Applica anche agli altri episodi di questa release",

        # --- Triage automatico Film/Serie ---
        "ambiguous_title": "Film o Serie TV?",
        "ambiguous_msg": "Non riesco a stabilire con certezza se «{name}» sia un film o un episodio di una serie.",
        "ambiguous_btn_movie": "È un film",
        "ambiguous_btn_series": "È un episodio di una serie",
        "triage_result": "Aggiunti: {movies} in Film, {series} in Serie TV",
    },
    "en": {
        "app_title": f"MediaTidy v{VERSION} - Rename and Organize Movies and TV Series",
        "tab_movies": "Movies",
        "tab_series": "TV Series",
        "options": "⚙ Options",
        "format_btn": "Name Format",
        "credits_btn": "Credits & Privacy",
        "log_btn": "Log",
        "file_action": "File action:",
        "move": "Move (delete original)",
        "copy": "Copy (keep original)",
        "action_move_short": "Move",
        "action_copy_short": "Copy",
        "exec_sel_suffix": "{n} sel.",
        "exec_all_suffix": "all ({n})",
        "drag_drop": "Drag & drop video files or folders here",
        "add_files": "Add files…",
        "add_dir": "Add folder…",
        "remove_sel": "Remove selected",
        "clear_all": "Clear all",
        "test": "Test",
        "execute": "Run (Move/Copy)",
        "ready_status": "Ready",
        "no_video_found": "No new video files found",

        "opts_title": "Options & Settings",
        "tmdb_key": "TMDB API Key:",
        "tmdb_link_help": "Don't have a key? <a href='https://developer.themoviedb.org/docs/getting-started'>Get it here (TMDB Guide)</a>",
        "dest_folder": "Destination:",
        "browse": "Browse…",
        "tmdb_search_lang": "TMDB Search Language:",
        "capitalization": "Capitalization Rule:",
        "cap_1": "First letter of first word only",
        "cap_2": "Capitalize all words",
        "cap_3": "Capitalize all words except articles/conjunctions",
        "unmount_chk": "Unmount drive when done (if mounted by the app)",
        "clean_dir_chk": "Delete source folder if empty (Move mode only)",
        "gui_lang_label": "Interface Language (Lingua GUI):",
        "logs_dir_label": "Logs folder:",
        "ok": "Confirm",

        "format_title": "Name Format",
        "format_tab_movies": "Movies",
        "format_tab_series": "TV Series",
        "dest_movies_label": "Movies destination:",
        "dest_series_label": "TV Series destination:",
        "title_mode_label": "Title:",
        "title_mode_original": "Original title only",
        "title_mode_localized": "Localized title only",
        "title_mode_orig_loc": "Both — Original (Localized)",
        "title_mode_loc_orig": "Both — Localized (Original)",
        "movie_include_tmdb_id": "Include the TMDB ID in the folder name",
        "movie_tmdb_id_note": "If disabled, same-named titles with the same year may end up in the same folder.",
        "movie_include_country": "Include the production country in the folder name",
        "movie_include_director": "Include the director in the folder name",
        "movie_download_poster": "Download the poster into the destination folder",
        "series_include_tmdb_id": "Include the TMDB ID in the show's folder name",
        "series_include_country": "Include the production country (format: Title (Country, Year))",
        "series_tmdb_id_note": "If disabled, same-named shows with the same year may end up in the same folder.",
        "series_include_episode_title": "Include the episode title in the filename",
        "series_download_show_poster": "Download the show poster",
        "series_download_season_poster": "Download the season poster",

        "reset_auto_name": "Reset to automatic name",
        "series_ctx_edit_unified": "Edit episode and name...",
        "series_edit_unified_title": "Edit Episode and Name",
        "customize_name_chk": "Also customize name and folder",

        "dup_title": "File/Folder Already Exists",
        "dup_msg": "<b>Warning:</b> File or folder already exists at destination:<br><br><b>Folder:</b> {folder}<br><b>File:</b> {file}<br><br>How would you like to proceed?",
        "dup_opt1": "1. Overwrite existing file",
        "dup_opt2": "2. Auto-rename (Add suffix _1, _2...)",
        "dup_opt3": "3. Custom edit name/folder...",
        "dup_opt4": "4. Skip this file",
        "dup_apply_all": "Apply choice to all remaining duplicates",

        "non_empty_dir_title": "Source folder not empty",
        "non_empty_dir_msg": "<b>Warning:</b> The source folder contains remaining files:<br><br><b>Folder:</b> {folder}<br><b>Total remaining size:</b> {size}<br><br>Do you still want to delete it?",
        "btn_yes": "Yes, delete",
        "btn_yes_to_all": "Yes to all",
        "btn_no": "No, skip",
        "btn_open_folder": "Open folder",

        "search_btn": "Search",
        "skip_file": "Skip this file",
        "ctx_custom": "Custom edit (Name and Folder)...",
        "ctx_tmdb": "Edit TMDB Code...",
        "ctx_lang": "Search in another language for this file...",
        "ctx_overwrite": "Force Overwrite",
        "ctx_suffix": "Add Suffix _copy",
        "ctx_remove": "Remove from list",
        "custom_edit_title": "Custom Edit",
        "new_filename": "New Filename:",
        "dest_subfolder": "Destination Folder:",
        "edit_tmdb_title": "Edit TMDB Code",
        "tmdb_id_label": "TMDB Unique ID:",
        "select_lang_title": "Select TMDB Search Language",
        "lang_label": "Language:",

        "missing_key_title": "Missing API Key",
        "missing_key_msg": "Please enter your TMDB API Key in Options.",
        "missing_dest_title": "Missing Destination",
        "missing_dest_msg": "Please set the destination folder in Options.",
        "done_test": "Test completed: {ready} files ready",
        "done_action": "Operation completed: {done} files processed",
        "notif_title": "MediaTidy - Operation Completed",
        "notif_body": "Successfully processed {done} files to destination!",
        "unmounted_msg": " — drive unmounted",
        "error_title": "Error",
        "busy_title": "Operation in progress",
        "busy_msg": "Please wait for completion before closing.",

        "status_testing": "Testing…",
        "status_already_exists": "Already exists",
        "status_ready": "Ready",
        "status_ready_inplace": "Ready (In-Place)",
        "status_skipped": "Skipped",
        "status_skipped_dup": "Skipped (Duplicate)",
        "status_moving": "Moving…",
        "status_copying": "Copying…",
        "status_renaming": "Renaming In-Place…",
        "status_done_moved": "Done (Moved)",
        "status_done_copied": "Done (Copied)",
        "status_done_inplace": "Done (Renamed)",
        "status_ready_custom": "Ready (Custom)",
        "status_ready_overwrite": "Ready (Overwrite)",
        "status_ready_suffix": "Ready (Suffix)",
        "status_to_test": "To test",
        "status_error": "Error",
        "status_tmdb_error": "TMDB ID error",
        "status_id_tmdb": "TMDB ID",
        "copy_suffix": "_copy",
        "invalid_custom_title": "Invalid values",
        "invalid_custom_msg": "The filename is empty or contains path separators, or the folder is absolute or contains '..'.",

        # --- Movies ---
        "movie_col_orig": "Original File",
        "movie_col_new": "New Name",
        "movie_col_dest": "Destination Folder",
        "movie_col_tmdb": "TMDB Code",
        "movie_col_status": "Status",
        "movie_choice_title": "Confirm Movie",
        "movie_no_res": "No results found",
        "movie_uncertain": "Uncertain result",
        "movie_choice_msg": " for «{guessed}».\nSelect the correct movie or search with another title.",

        # --- TV Series ---
        "series_col_orig": "Source file / folder",
        "series_col_show": "Show",
        "series_col_ep": "Season/Episode",
        "series_col_new": "New Name",
        "series_col_dest": "Destination Folder",
        "series_col_tmdb": "TMDB Code (show)",
        "series_col_status": "Status",
        "series_choice_title": "Confirm TV Show",
        "series_no_res": "No results found",
        "series_uncertain": "Uncertain result",
        "series_choice_msg": " for «{guessed}».\nSelect the correct show or search with another title.",
        "series_ctx_edit_ep": "Edit Season/Episode...",
        "series_edit_ep_title": "Edit Season/Episode",
        "series_season_label": "Season:",
        "series_episode_label": "Episode (or first of a range):",
        "series_episode_last_label": "Last episode (range, optional):",
        "series_status_unknown_ep": "Episode not recognized",
        "series_status_clip_skipped": "Ignored (sample/trailer)",
        "series_add_release": "Add release…",
        "series_apply_release_chk": "Also apply to other episodes in this release",

        # --- Automatic Movie/Series triage ---
        "ambiguous_title": "Movie or TV Series?",
        "ambiguous_msg": "I can't reliably tell whether «{name}» is a movie or a TV episode.",
        "ambiguous_btn_movie": "It's a movie",
        "ambiguous_btn_series": "It's a TV episode",
        "triage_result": "Added: {movies} to Movies, {series} to TV Series",
    },
}


def tr(key, **kwargs):
    g_lang = CONFIG.get("gui_lang", "it")
    lang_dict = STRINGS.get(g_lang, STRINGS["it"])
    text = lang_dict.get(key, STRINGS["it"].get(key, key))
    if kwargs:
        return text.format(**kwargs)
    return text
